/**
 * @file esp32_isf15acp4_test_config.hpp
 * @brief Shared pin and SPI constants for ISF15ACP4 ESP32 examples.
 */
#pragma once

#include <cstdint>

#ifndef CONFIG_ISF15ACP4_SPI_HOST
#define CONFIG_ISF15ACP4_SPI_HOST 1
#endif
#ifndef CONFIG_ISF15ACP4_PIN_MOSI
#define CONFIG_ISF15ACP4_PIN_MOSI 11
#endif
#ifndef CONFIG_ISF15ACP4_PIN_SCLK
#define CONFIG_ISF15ACP4_PIN_SCLK 12
#endif
#ifndef CONFIG_ISF15ACP4_PIN_CS
#define CONFIG_ISF15ACP4_PIN_CS 10
#endif
#ifndef CONFIG_ISF15ACP4_PIN_DC
#define CONFIG_ISF15ACP4_PIN_DC 13
#endif
#ifndef CONFIG_ISF15ACP4_PIN_RES
#define CONFIG_ISF15ACP4_PIN_RES 14
#endif
#ifndef CONFIG_ISF15ACP4_PIN_VCC_EN
#define CONFIG_ISF15ACP4_PIN_VCC_EN 9
#endif
#ifndef CONFIG_ISF15ACP4_PIN_SWITCH
#define CONFIG_ISF15ACP4_PIN_SWITCH 8
#endif

#ifndef ISF15ACP4_SPI_CLOCK_HZ
#define ISF15ACP4_SPI_CLOCK_HZ 6000000
#endif
